In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets

a = tf.random.normal([4,35,8])
b = tf.random.normal([6,35,8])
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(10, 35, 8), dtype=float32, numpy=
array([[[ 1.4943812e+00, -1.0689557e+00, -1.4468516e-01, ...,
         -8.9813077e-01,  7.1446818e-01, -5.1167327e-01],
        [ 4.0617549e-01,  1.9447160e-01,  1.3882638e+00, ...,
         -6.8328923e-01,  3.0275923e-01, -9.2239010e-01],
        [-4.7814623e-01,  5.0739783e-01,  1.0334204e+00, ...,
          4.4585881e-01,  4.9753138e-01, -4.8230731e-01],
        ...,
        [ 1.2295846e+00, -7.2968066e-01,  7.6135278e-01, ...,
         -1.3579459e+00, -9.2926913e-01, -1.1803694e+00],
        [ 6.6986209e-01, -1.4186858e-01,  1.2820111e-01, ...,
          4.2654783e-01, -5.8643770e-01, -1.1245253e+00],
        [ 9.9050426e-01, -1.2989405e+00,  7.0221388e-01, ...,
          9.0291619e-01, -5.6451589e-01,  4.6851435e-01]],

       [[-4.9568605e-01,  1.0589266e+00, -1.8776160e-01, ...,
         -1.1840703e+00,  1.3982855e+00,  1.6789678e+00],
        [ 2.1973953e+00, -1.1919951e-01, -3.0684212e-01, ...,
          2.4821788e-01,  1.29

In [6]:
a = tf.random.normal([10,35,4])
b = tf.random.normal([10,35,4])
tf.concat([a,b],axis=2)


<tf.Tensor: shape=(10, 35, 8), dtype=float32, numpy=
array([[[-1.471919  ,  0.17173839, -0.84727997, ..., -0.6871366 ,
         -1.9776644 ,  2.892204  ],
        [ 0.35440478, -0.39133218, -0.55299723, ..., -1.8756382 ,
         -0.2830002 , -0.6848558 ],
        [-0.10297974, -0.69229275,  0.9775489 , ...,  0.5609458 ,
         -0.24932125,  0.8437029 ],
        ...,
        [ 0.46218652,  2.8203213 , -1.3266944 , ...,  0.93299204,
         -1.9050131 , -0.85676444],
        [-1.0363553 , -0.96913624,  2.060943  , ..., -1.0700233 ,
         -0.4474505 ,  0.4497533 ],
        [-0.5378466 ,  0.5112628 , -0.2150082 , ..., -1.0884148 ,
         -0.03495297,  0.78778696]],

       [[-0.1864186 ,  0.44139382,  1.8030177 , ...,  1.287443  ,
         -0.6033025 ,  0.71337515],
        [ 0.10406426,  0.06706546, -0.78139335, ...,  0.0372722 ,
          0.7319234 , -0.84491473],
        [-0.5091366 ,  0.21995896, -0.04483243, ..., -0.65594184,
          0.02519657,  2.6667712 ],
        ...,
 